server:
  port: 9081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud_order?userUnicode=true&characterEncoding=utf-8&serverTimeZone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderserver
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.250.10:8080
      web-context-unify: false
    nacos:
      server-addr: 192.168.250.10:8848
      discovery:
        cluster-name: HZ # 配置服务集群
        namespace: 1c5ce879-6c87-45f1-9abf-4c1a62257cd0 #  命名空间进行环境隔离
#        ephemeral: false # 是否临时实例 临时实例采用心跳模式，异常就被剔除，非临时实例采用主动检测模式，一直都在但是爆红


# 针对user服务的负载均衡规则
orderserver:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # nacos同一集群负载均衡规则

ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: # 指定饥饿加载的服务
      - userserver

mybatis:
  type-aliases-package: com.ppx.order.entity
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

logging:
  level:
    com.ppx: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

# feign配置
# 方式一
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  sentinel:
    enabled: false # 开启feign对sentinel的支持
#  client: # 另一种feign配置
#    config:
##      userserver: # 针对某个微服务的配置
#      default: # 这里用default就是全局配置，如果是写服务名称，则是针对某个微服务的配置
#        loggerLevel: BASIC #  日志级别